### ISSUE TITLE
AttributeError: 'WorkflowClient' object has no attribute 'export_workflow_json'

### ISSUE THREAD

**Issue by PHemarajata** [phac-nml/snvphyl-galaxy-cli#6]
Hi! I ran into the error below and was wondering if someone could help me figure it out. Thank you!

(base) [sysadmin@phlabbiocovid Abam-SCHH-2021_HF-2021-162]$ python /home/sysadmin/snvphyl-galaxy-cli/bin/snvphyl.py --deploy-docker --fastq-dir /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162 --reference-file 470.9514.fna --min-coverage 15 --output-dir output1

Deploying Docker Container
==========================
Running 'docker run --detach --publish 48888:80 --volume /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162:/snvphyl-data/fastq phacnml/snvphyl-galaxy-1.0.1:1.0.1b'
Docker id 0d3cb945c8cef556522372c4b8db2d2951afc370286e3431944af15755c9ba4c
Waiting for docker to complete launching Galaxy on port 48888 .....finished.  Galaxy in Docker has (hopefully) started successfully.
Took 0.29 minutes to deploy docker

Examining input fastq files
===========================
Structuring data in directory '/home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162' like:
F14870-LAC-M04759-210330_S11_L001: paired {forward: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/F14870-LAC-M04759-210330_S11_L001_R1_001.fastq.gz, reverse: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/F14870-LAC-M04759-210330_S11_L001_R2_001.fastq.gz}
H1260_LAC-M04759-210308_S15_L001: paired {forward: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/H1260_LAC-M04759-210308_S15_L001_R1_001.fastq.gz, reverse: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/H1260_LAC-M04759-210308_S15_L001_R2_001.fastq.gz}
T29322-LAC-M05385-210302_S8_L001: paired {forward: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29322-LAC-M05385-210302_S8_L001_R1_001.fastq.gz, reverse: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29322-LAC-M05385-210302_S8_L001_R2_001.fastq.gz}
T29323-LAC-M05385-210302_S9_L001: paired {forward: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29323-LAC-M05385-210302_S9_L001_R1_001.fastq.gz, reverse: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29323-LAC-M05385-210302_S9_L001_R2_001.fastq.gz}
T29324-LAC-M05385-210302_S10_L001: paired {forward: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29324-LAC-M05385-210302_S10_L001_R1_001.fastq.gz, reverse: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29324-LAC-M05385-210302_S10_L001_R2_001.fastq.gz}
T29325-LAC-M05385-210302_S11_L001: paired {forward: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29325-LAC-M05385-210302_S11_L001_R1_001.fastq.gz, reverse: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29325-LAC-M05385-210302_S11_L001_R2_001.fastq.gz}
T29326-LAC-M05385-210302_S12_L001: paired {forward: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29326-LAC-M05385-210302_S12_L001_R1_001.fastq.gz, reverse: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/T29326-LAC-M05385-210302_S12_L001_R2_001.fastq.gz}
W52987-LAC-M05385-210426_S16_L001: paired {forward: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/W52987-LAC-M05385-210426_S16_L001_R1_001.fastq.gz, reverse: /home/sysadmin/Documents/Microbial_WGS_analysis/Abam-SCHH-2021_HF-2021-162/W52987-LAC-M05385-210426_S16_L001_R2_001.fastq.gz}

Set up workflow input
=====================
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, snv_abundance_ratio, 0.75}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, coverage, 15}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/verify_map/verify_map/1.8.0, mindepth, 15}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, mean_mapping, 30}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/find_repeats/findrepeat/1.8.0, length, 150}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/find_repeats/findrepeat/1.8.0, pid, 90}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, use_density_filter.threshold, 2}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, use_density_filter.window_size, 500}

Undeploying and cleaning up Docker Container
=============================================
Running 'docker rm -f -v 0d3cb945c8cef556522372c4b8db2d2951afc370286e3431944af15755c9ba4c'
0d3cb945c8cef556522372c4b8db2d2951afc370286e3431944af15755c9ba4c
Traceback (most recent call last):
  File "/home/sysadmin/snvphyl-galaxy-cli/bin/snvphyl.py", line 1302, in <module>
    main(snvphyl_version_settings, **dic)
  File "/home/sysadmin/snvphyl-galaxy-cli/bin/snvphyl.py", line 973, in main
    main_galaxy(url, key, snvphyl_version, workflow_id, fastq_dir, fastq_history_name, reference_file, run_name, relative_snv_abundance, min_coverage, min_mean_mapping,
  File "/home/sysadmin/snvphyl-galaxy-cli/bin/snvphyl.py", line 1061, in main_galaxy
    validate_workflow(gi,snvphyl_workflow,workflow_settings,workflow_parameters)
  File "/home/sysadmin/snvphyl-galaxy-cli/bin/snvphyl.py", line 656, in validate_workflow
    workflow_json=gi.workflows.export_workflow_json(snvphyl_workflow['id'])
AttributeError: 'WorkflowClient' object has no attribute 'export_workflow_json'

**Comment by apetkau** [comment]
The message `AttributeError: 'WorkflowClient' object has no attribute 'export_workflow_json'` makes me think that one of the libraries this software depends on (`bioblend`) has changed it's API. Could you try installing an older version and seeing if this works. That is:

```
pip install bioblend==0.7.0
```
