### ISSUE TITLE
running snvphyl by CLI produces an error 

### ISSUE THREAD

**Issue by avpg3** [phac-nml/snvphyl-galaxy-cli#8]
Dear contact, 
I am running the following SNVPhyl command (see below) and I get a random error that stops the workflow when is around ~80-87% complete. I am running the analysis for > 80 libraries and I haven't been able to complete the workflow; I suspect it has to do with resources allocated to the docker, but I don't know how to pass more resources for it to complete the whole process. Any help will be greatly appreciated!

command:
bin/snvphyl.py --deploy-docker --min-coverage 5 --fastq-dir /fastqs/group_3a --reference-file ASM101963v1_genomic.fasta --output-dir ASM101963v1_output_group_3a --docker-cpus 72

Error:
Waiting for workflow completion 
===============================
percent complete (can initially decrease as more jobs are scheduled by Galaxy): 0...32.394366197183096...32.394366197183096...32.394366197183096...33.80281690140845...35.2112676056338...35.2112676056338...39.436619718309856...39.436619718309856...45.070422535211264...47.88732394366197...52.11267605633803...57.74647887323944...60.563380281690144...60.563380281690144...64.78873239436619...67.6056338028169...67.6056338028169...70.4225352112676...70.4225352112676...70.4225352112676...70.4225352112676...70.4225352112676...70.4225352112676...71.83098591549296...71.83098591549296...73.2394366197183...73.2394366197183...73.2394366197183...73.2394366197183...73.2394366197183...73.2394366197183...76.05633802816901...76.05633802816901...77.46478873239437...77.46478873239437...77.46478873239437...77.46478873239437...77.46478873239437...77.46478873239437...77.46478873239437...77.46478873239437...81.69014084507042...81.69014084507042...81.69014084507042...84.50704225352112...87.32394366197182...87.32394366197182...87.32394366197182...87.32394366197182...87.32394366197182...87.32394366197182...87.32394366197182...87.32394366197182...87.32394366197182...87.32394366197182...87.32394366197182
**Error occured while running workflow, downloading existing output files**

Searching for dataset with name filterStats.txt
Searching for dataset with name mappingQuality.txt
Searching for dataset with name phylogeneticTree.newick
Searching for dataset with name snvAlignment.phy
Searching for dataset with name snvMatrix.tsv
Exception occured when downloading snvMatrix.tsv, skipping...
DatasetStateException("Dataset state is not 'ok'. Dataset id: fa6833a4eadf9064, current state: error"): Dataset state is not 'ok'. Dataset id: fa6833a4eadf9064, current state: error
Searching for dataset with name snvTable.tsv
Searching for dataset with name vcf2core.tsv

Writing Galaxy provenance info

Undeploying and cleaning up Docker Container
=============================================
Running 'docker rm -f -v 227c86415953294e02b471ade660568fe8a452bc6dfbbb432185589312f027e5'
227c86415953294e02b471ade660568fe8a452bc6dfbbb432185589312f027e5
Traceback (most recent call last):
  File "bin/snvphyl.py", line 1302, in <module>
    main(snvphyl_version_settings, **dic)
  File "bin/snvphyl.py", line 974, in main
    repeat_minimum_length, repeat_minimum_pid, filter_density_window, filter_density_threshold, invalid_positions_file, output_dir)
  File "bin/snvphyl.py", line 1193, in main_galaxy
    raise Exception('error occured in workflow, history=['+history_name+'], problematic datasets=["'+'"; "'.join(dataset_error_list)+'"]')
Exception: error occured in workflow, history=[snvphyl-ASM101963v1_genomic-2024-01-17-run], problematic datasets=["snvMatrix.tsv"]

**Comment by apetkau** [comment]
Hello @avpg3 , try passing `--keep-docker` so that the Docker/Galaxy instance is not shutdown after failure. You can then login to the instance of Galaxy running with the following credentials:

* URL: http://localhost:48888/
* Username: admin@galaxy.org
* Password: admin

From there you can take more detailed looks on what is causing issues (https://snvphyl.readthedocs.io/en/latest/user/usage/#managing-errors)
